# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20181205000153) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "draft_players", force: :cascade do |t|
    t.bigint "player_id"
    t.bigint "team_id"
    t.integer "age"
    t.integer "clutch_trait"
    t.integer "dev_trait"
    t.integer "draft_num"
    t.integer "draft_pick"
    t.integer "draft_round"
    t.integer "intangible_grade"
    t.integer "physical_grade"
    t.integer "player_best_ovr"
    t.integer "player_scheme_ovr"
    t.integer "production_grade"
    t.integer "scheme"
    t.integer "team_scheme_ovr"
    t.integer "years_pro"
    t.integer "contract_bonus"
    t.integer "contract_length"
    t.integer "contract_salary"
    t.string "name"
    t.string "position"
  end

  create_table "players", id: :bigint, default: nil, force: :cascade do |t|
    t.bigint "presentation_id"
    t.bigint "team_id"
    t.integer "accel_rating"
    t.integer "age"
    t.integer "agility_rating"
    t.integer "aware_rating"
    t.integer "b_cv_rating"
    t.integer "big_hit_trait"
    t.integer "birth_day"
    t.integer "birth_month"
    t.integer "birth_year"
    t.integer "block_shed_rating"
    t.integer "break_sack_rating"
    t.integer "break_tackle_rating"
    t.integer "c_it_rating"
    t.integer "cap_hit"
    t.integer "cap_release_net_savings"
    t.integer "cap_release_penalty"
    t.integer "carry_rating"
    t.integer "catch_rating"
    t.integer "clutch_trait"
    t.integer "conf_rating"
    t.integer "contract_bonus"
    t.integer "contract_length"
    t.integer "contract_salary"
    t.integer "contract_years_left"
    t.integer "cover_ball_trait"
    t.integer "d_l_bull_rush_trait"
    t.integer "d_l_spin_trait"
    t.integer "d_l_swim_trait"
    t.integer "desired_bonus"
    t.integer "desired_length"
    t.integer "desired_salary"
    t.integer "dev_trait"
    t.integer "draft_pick"
    t.integer "draft_round"
    t.integer "drop_open_pass_trait"
    t.integer "durability_grade"
    t.integer "elusive_rating"
    t.integer "experience_points"
    t.integer "feet_in_bounds_trait"
    t.integer "fight_for_yards_trait"
    t.integer "finesse_moves_rating"
    t.integer "force_pass_trait"
    t.integer "h_p_catch_trait"
    t.integer "height"
    t.integer "high_motor_trait"
    t.integer "hit_power_rating"
    t.integer "home_state"
    t.integer "impact_block_rating"
    t.integer "injury_length"
    t.integer "injury_rating"
    t.integer "injury_type"
    t.integer "intangible_grade"
    t.integer "jersey_num"
    t.integer "juke_move_rating"
    t.integer "jump_rating"
    t.integer "kick_acc_rating"
    t.integer "kick_power_rating"
    t.integer "kick_ret_rating"
    t.integer "l_b_style_trait"
    t.integer "lead_block_rating"
    t.integer "legacy_score"
    t.integer "man_cover_rating"
    t.integer "pass_block_finesse_rating"
    t.integer "pass_block_power_rating"
    t.integer "pass_block_rating"
    t.integer "penalty_trait"
    t.integer "physical_grade"
    t.integer "play_action_rating"
    t.integer "play_ball_trait"
    t.integer "play_rec_rating"
    t.integer "player_best_ovr"
    t.integer "player_scheme_ovr"
    t.integer "portrait_id"
    t.integer "pos_catch_trait"
    t.integer "power_moves_rating"
    t.integer "predict_trait"
    t.integer "press_rating"
    t.integer "production_grade"
    t.integer "pursuit_rating"
    t.integer "q_b_style_trait"
    t.integer "re_sign_status"
    t.integer "release_rating"
    t.integer "rookie_year"
    t.integer "route_run_deep_rating"
    t.integer "route_run_med_rating"
    t.integer "route_run_short_rating"
    t.integer "run_block_finesse_rating"
    t.integer "run_block_power_rating"
    t.integer "run_block_rating"
    t.integer "run_style"
    t.integer "scheme"
    t.integer "sense_pressure_trait"
    t.integer "size_grade"
    t.integer "skill_points"
    t.integer "spec_catch_rating"
    t.integer "speed_rating"
    t.integer "spin_move_rating"
    t.integer "stamina_rating"
    t.integer "stiff_arm_rating"
    t.integer "strength_rating"
    t.integer "strip_ball_trait"
    t.integer "tackle_rating"
    t.integer "team_scheme_ovr"
    t.integer "throw_acc_deep_rating"
    t.integer "throw_acc_mid_rating"
    t.integer "throw_acc_rating"
    t.integer "throw_acc_short_rating"
    t.integer "throw_away_trait"
    t.integer "throw_on_run_rating"
    t.integer "throw_power_rating"
    t.integer "throw_under_pressure_rating"
    t.integer "tight_spiral_trait"
    t.integer "tough_rating"
    t.integer "truck_rating"
    t.integer "weight"
    t.integer "y_ac_catch_trait"
    t.integer "years_pro"
    t.integer "zone_cover_rating"
    t.string "college"
    t.string "first_name"
    t.string "home_town"
    t.string "last_name"
    t.string "position"
    t.boolean "is_active"
    t.boolean "is_free_agent"
    t.boolean "is_on_ir"
    t.boolean "is_on_practice_squad"
  end

  create_table "teams", id: :bigint, default: nil, force: :cascade do |t|
    t.bigint "conference_id"
    t.bigint "division_id"
    t.bigint "logo_id"
    t.integer "away_losses"
    t.integer "away_ties"
    t.integer "away_wins"
    t.integer "calendar_year"
    t.integer "cap_available"
    t.integer "cap_room"
    t.integer "cap_spent"
    t.integer "conf_losses"
    t.integer "conf_ties"
    t.integer "conf_wins"
    t.integer "def_pass_yds"
    t.integer "def_pass_yds_rank"
    t.integer "def_rush_yds"
    t.integer "def_rush_yds_rank"
    t.integer "def_scheme"
    t.integer "def_total_yds"
    t.integer "def_total_yds_rank"
    t.integer "div_losses"
    t.integer "div_ties"
    t.integer "div_wins"
    t.integer "home_losses"
    t.integer "home_ties"
    t.integer "home_wins"
    t.integer "injury_count"
    t.integer "net_pts"
    t.integer "off_pass_yds"
    t.integer "off_pass_yds_rank"
    t.integer "off_rush_yds"
    t.integer "off_rush_yds_rank"
    t.integer "off_scheme"
    t.integer "off_total_yds"
    t.integer "off_total_yds_rank"
    t.integer "ovr_rating"
    t.integer "playoff_status"
    t.integer "prev_rank"
    t.integer "primary_color"
    t.integer "pts_against"
    t.integer "pts_against_rank"
    t.integer "pts_for"
    t.integer "pts_for_rank"
    t.integer "rank"
    t.integer "season_index"
    t.integer "secondary_color"
    t.integer "seed"
    t.integer "stage_index"
    t.integer "t_o_diff"
    t.integer "team_ovr"
    t.integer "total_losses"
    t.integer "total_ties"
    t.integer "total_wins"
    t.integer "week_index"
    t.integer "win_loss_streak"
    t.decimal "win_pct"
    t.string "abbr_name"
    t.string "city_name"
    t.string "conference_name"
    t.string "display_name"
    t.string "div_name"
    t.string "division_name"
    t.string "nick_name"
    t.string "team_name"
    t.string "user_name"
  end

end
