class Import::Archetypes < ApplicationService
  def call
    Archetype.delete_all
    Archetype.create(values)
  end


  private

  def values
    [
      {id: 1, position: "QB", name: "Field General", aware_rating: 16, throw_acc_deep_rating: 12, throw_acc_mid_rating: 18, play_action_rating: 3, throw_acc_short_rating: 18, throw_on_run_rating: 3, throw_power_rating: 25, throw_under_pressure_rating: 5},
      {id: 2, position: "QB", name: "Improviser", accel_rating: 1, agility_rating: 2, aware_rating: 14, throw_acc_deep_rating: 3, throw_acc_mid_rating: 18, play_action_rating: 11, throw_acc_short_rating: 24, speed_rating: 2, throw_on_run_rating: 5, throw_power_rating: 15, throw_under_pressure_rating: 5},
      {id: 3, position: "QB", name: "Scrambler", accel_rating: 3, agility_rating: 2, aware_rating: 7, break_sack_rating: 10, carry_rating: 3, throw_acc_mid_rating: 14, throw_acc_short_rating: 15, speed_rating: 6, throw_on_run_rating: 10, throw_power_rating: 23, throw_under_pressure_rating: 7},
      {id: 4, position: "QB", name: "Strong Arm", aware_rating: 12, break_sack_rating: 3, throw_acc_deep_rating: 18, throw_acc_mid_rating: 22, play_action_rating: 2, throw_power_rating: 33, throw_under_pressure_rating: 10},
      {id: 5, position: "HB", name: "Elusive Back", accel_rating: 13, agility_rating: 11, aware_rating: 8, b_cv_rating: 10, break_tackle_rating: 6, carry_rating: 11, elusive_rating: 10, juke_move_rating: 9, speed_rating: 13, spin_move_rating: 9},
      {id: 6, position: "HB", name: "Power Back", accel_rating: 9, agility_rating: 5, aware_rating: 8, b_cv_rating: 10, break_tackle_rating: 12, carry_rating: 13, speed_rating: 9, stiff_arm_rating: 11, strength_rating: 10, truck_rating: 13},
      {id: 7, position: "HB", name: "Receiving Back", accel_rating: 12, agility_rating: 8, aware_rating: 9, b_cv_rating: 5, carry_rating: 7, catch_rating: 14, c_it_rating: 8, elusive_rating: 4, juke_move_rating: 5, release_rating: 1, route_run_short_rating: 10, speed_rating: 12, spin_move_rating: 5},
      {id: 8, position: "FB", name: "Blocking", accel_rating: 2, agility_rating: 2, aware_rating: 10, break_tackle_rating: 6, carry_rating: 5, catch_rating: 2, c_it_rating: 2, impact_block_rating: 20, lead_block_rating: 7, pass_block_rating: 4, pass_block_finesse_rating: 1, pass_block_power_rating: 1, run_block_rating: 10, run_block_finesse_rating: 3, run_block_power_rating: 5, route_run_short_rating: 5, speed_rating: 1, strength_rating: 7, truck_rating: 7},
      {id: 9, position: "FB", name: "Utility", accel_rating: 5, agility_rating: 5, aware_rating: 10, b_cv_rating: 6, break_tackle_rating: 4, carry_rating: 7, catch_rating: 8, c_it_rating: 2, elusive_rating: 3, impact_block_rating: 11, lead_block_rating: 5, pass_block_rating: 2, run_block_rating: 3, route_run_short_rating: 9, speed_rating: 5, stiff_arm_rating: 4, strength_rating: 6, truck_rating: 5},
      {id: 10, position: "WR", name: "Deep Threat", accel_rating: 12, agility_rating: 8, aware_rating: 9, catch_rating: 13, c_it_rating: 7, route_run_deep_rating: 15, elusive_rating: 2, juke_move_rating: 1, jump_rating: 1, route_run_med_rating: 6, release_rating: 9, spec_catch_rating: 4, speed_rating: 12, spin_move_rating: 1},
      {id: 11, position: "WR", name: "Physical", accel_rating: 9, agility_rating: 7, aware_rating: 10, break_tackle_rating: 1, catch_rating: 13, c_it_rating: 10, jump_rating: 5, route_run_med_rating: 5, release_rating: 9, route_run_short_rating: 9, spec_catch_rating: 9, speed_rating: 9, stiff_arm_rating: 1, strength_rating: 2, truck_rating: 1},
      {id: 12, position: "WR", name: "Route Runner", accel_rating: 8, agility_rating: 6, aware_rating: 7, break_tackle_rating: 1, carry_rating: 2, catch_rating: 14, c_it_rating: 15, elusive_rating: 1, jump_rating: 3, route_run_med_rating: 10, release_rating: 5, route_run_short_rating: 13, spec_catch_rating: 2, speed_rating: 8, stiff_arm_rating: 2, strength_rating: 2, truck_rating: 1},
      {id: 13, position: "WR", name: "Slot", accel_rating: 12, agility_rating: 7, aware_rating: 10, break_tackle_rating: 1, carry_rating: 1, catch_rating: 13, c_it_rating: 14, route_run_deep_rating: 3, elusive_rating: 2, juke_move_rating: 1, route_run_med_rating: 9, route_run_short_rating: 16, speed_rating: 10, spin_move_rating: 1},
      {id: 14, position: "TE", name: "Blocking", aware_rating: 9, break_tackle_rating: 2, catch_rating: 3, c_it_rating: 3, impact_block_rating: 9, lead_block_rating: 8, route_run_med_rating: 4, pass_block_rating: 8, pass_block_finesse_rating: 6, pass_block_power_rating: 6, run_block_rating: 10, run_block_finesse_rating: 9, run_block_power_rating: 9, route_run_short_rating: 5, stiff_arm_rating: 2, strength_rating: 6, truck_rating: 1},
      {id: 15, position: "TE", name: "Possession", accel_rating: 4, agility_rating: 3, aware_rating: 9, b_cv_rating: 1, break_tackle_rating: 2, catch_rating: 10, c_it_rating: 14, impact_block_rating: 4, lead_block_rating: 2, route_run_med_rating: 6, pass_block_rating: 3, pass_block_finesse_rating: 2, pass_block_power_rating: 2, release_rating: 2, run_block_rating: 5, run_block_finesse_rating: 4, run_block_power_rating: 4, route_run_short_rating: 12, spec_catch_rating: 1, speed_rating: 3, stiff_arm_rating: 2, strength_rating: 4, truck_rating: 1},
      {id: 16, position: "TE", name: "Vertical Threat", accel_rating: 7, agility_rating: 4, aware_rating: 9, b_cv_rating: 2, break_tackle_rating: 3, catch_rating: 11, c_it_rating: 8, route_run_deep_rating: 5, elusive_rating: 2, jump_rating: 3, route_run_med_rating: 9, pass_block_rating: 2, pass_block_finesse_rating: 1, pass_block_power_rating: 1, release_rating: 3, run_block_rating: 3, run_block_finesse_rating: 3, run_block_power_rating: 3, route_run_short_rating: 7, spec_catch_rating: 4, speed_rating: 7, stiff_arm_rating: 2, truck_rating: 1},
      {id: 17, position: "LT", name: "Agile", accel_rating: 2, agility_rating: 3, aware_rating: 10, impact_block_rating: 4, lead_block_rating: 2, pass_block_rating: 6, pass_block_finesse_rating: 25, run_block_rating: 8, run_block_finesse_rating: 24, speed_rating: 3, strength_rating: 13},
      {id: 18, position: "LT", name: "Pass Protector", accel_rating: 2, agility_rating: 2, aware_rating: 14, impact_block_rating: 2, pass_block_rating: 8, pass_block_finesse_rating: 28, pass_block_power_rating: 28, speed_rating: 2, strength_rating: 14},
      {id: 19, position: "LT", name: "Power", accel_rating: 2, agility_rating: 2, aware_rating: 10, impact_block_rating: 4, lead_block_rating: 2, pass_block_rating: 4, pass_block_power_rating: 24, run_block_rating: 10, run_block_power_rating: 25, speed_rating: 2, strength_rating: 15},
      {id: 20, position: "LG", name: "Agile", accel_rating: 2, agility_rating: 3, aware_rating: 10, impact_block_rating: 7, lead_block_rating: 8, pass_block_rating: 4, pass_block_finesse_rating: 23, run_block_rating: 8, run_block_finesse_rating: 20, speed_rating: 2, strength_rating: 13},
      {id: 21, position: "LG", name: "Pass Protector", accel_rating: 2, agility_rating: 2, aware_rating: 14, impact_block_rating: 5, pass_block_rating: 5, pass_block_finesse_rating: 28, pass_block_power_rating: 28, speed_rating: 2, strength_rating: 14},
      {id: 22, position: "LG", name: "Power", accel_rating: 2, agility_rating: 2, aware_rating: 11, impact_block_rating: 7, lead_block_rating: 8, pass_block_rating: 2, pass_block_power_rating: 22, run_block_rating: 10, run_block_power_rating: 19, speed_rating: 2, strength_rating: 15},
      {id: 23, position: "C", name: "Agile", accel_rating: 2, agility_rating: 3, aware_rating: 15, impact_block_rating: 6, lead_block_rating: 4, pass_block_rating: 4, pass_block_finesse_rating: 21, run_block_rating: 8, run_block_finesse_rating: 22, speed_rating: 3, strength_rating: 12},
      {id: 24, position: "C", name: "Pass Protector", accel_rating: 2, agility_rating: 2, aware_rating: 18, impact_block_rating: 4, pass_block_rating: 5, pass_block_finesse_rating: 28, pass_block_power_rating: 28, strength_rating: 13},
      {id: 25, position: "C", name: "Power", accel_rating: 2, agility_rating: 2, aware_rating: 15, impact_block_rating: 6, lead_block_rating: 4, pass_block_rating: 2, pass_block_power_rating: 21, run_block_rating: 10, run_block_power_rating: 22, speed_rating: 2, strength_rating: 14},
      {id: 26, position: "RG", name: "Agile", accel_rating: 2, agility_rating: 3, aware_rating: 10, impact_block_rating: 7, lead_block_rating: 8, pass_block_rating: 4, pass_block_finesse_rating: 23, run_block_rating: 8, run_block_finesse_rating: 20, speed_rating: 2, strength_rating: 13},
      {id: 27, position: "RG", name: "Pass Protector", accel_rating: 2, agility_rating: 2, aware_rating: 14, impact_block_rating: 5, pass_block_rating: 5, pass_block_finesse_rating: 28, pass_block_power_rating: 28, speed_rating: 2, strength_rating: 14},
      {id: 28, position: "RG", name: "Power", accel_rating: 2, agility_rating: 2, aware_rating: 11, impact_block_rating: 7, lead_block_rating: 8, pass_block_rating: 2, pass_block_power_rating: 22, run_block_rating: 10, run_block_power_rating: 19, speed_rating: 2, strength_rating: 15},
      {id: 29, position: "RT", name: "Agile", accel_rating: 2, agility_rating: 3, aware_rating: 10, impact_block_rating: 4, lead_block_rating: 2, pass_block_rating: 6, pass_block_finesse_rating: 25, run_block_rating: 8, run_block_finesse_rating: 24, speed_rating: 3, strength_rating: 13},
      {id: 30, position: "RT", name: "Pass Protector", accel_rating: 2, agility_rating: 2, aware_rating: 14, impact_block_rating: 2, pass_block_rating: 8, pass_block_finesse_rating: 28, pass_block_power_rating: 28, speed_rating: 2, strength_rating: 14},
      {id: 31, position: "RT", name: "Power", accel_rating: 2, agility_rating: 2, aware_rating: 10, impact_block_rating: 4, lead_block_rating: 2, pass_block_rating: 4, pass_block_power_rating: 24, run_block_rating: 10, run_block_power_rating: 25, speed_rating: 2, strength_rating: 15},
      {id: 32, position: "LE", name: "Power Rusher", accel_rating: 10, agility_rating: 6, aware_rating: 7, hit_power_rating: 3, play_rec_rating: 7, power_moves_rating: 23, pursuit_rating: 7, speed_rating: 7, strength_rating: 15, tackle_rating: 15},
      {id: 33, position: "LE", name: "Run Stopper", accel_rating: 8, agility_rating: 5, aware_rating: 9, block_shed_rating: 18, finesse_moves_rating: 2, hit_power_rating: 3, play_rec_rating: 9, power_moves_rating: 2, pursuit_rating: 9, speed_rating: 5, strength_rating: 12, tackle_rating: 18},
      {id: 34, position: "LE", name: "Speed Rusher", accel_rating: 14, agility_rating: 9, aware_rating: 7, finesse_moves_rating: 23, hit_power_rating: 3, play_rec_rating: 7, pursuit_rating: 7, speed_rating: 10, strength_rating: 5, tackle_rating: 15},
      {id: 35, position: "RE", name: "Power Rusher", accel_rating: 10, agility_rating: 6, aware_rating: 7, hit_power_rating: 3, play_rec_rating: 7, power_moves_rating: 23, pursuit_rating: 7, speed_rating: 7, strength_rating: 15, tackle_rating: 15},
      {id: 36, position: "RE", name: "Run Stopper", accel_rating: 8, agility_rating: 5, aware_rating: 9, block_shed_rating: 18, finesse_moves_rating: 2, hit_power_rating: 3, play_rec_rating: 9, power_moves_rating: 2, pursuit_rating: 9, speed_rating: 5, strength_rating: 12, tackle_rating: 18},
      {id: 37, position: "RE", name: "Speed Rusher", accel_rating: 14, agility_rating: 9, aware_rating: 7, finesse_moves_rating: 23, hit_power_rating: 3, play_rec_rating: 7, pursuit_rating: 7, speed_rating: 10, strength_rating: 5, tackle_rating: 15},
      {id: 38, position: "DT", name: "Power Rusher", accel_rating: 6, agility_rating: 3, aware_rating: 9, block_shed_rating: 6, hit_power_rating: 3, play_rec_rating: 9, power_moves_rating: 22, pursuit_rating: 6, speed_rating: 3, strength_rating: 20, tackle_rating: 13},
      {id: 39, position: "DT", name: "Run Stopper", accel_rating: 6, agility_rating: 3, aware_rating: 8, block_shed_rating: 22, hit_power_rating: 3, play_rec_rating: 8, pursuit_rating: 8, speed_rating: 4, strength_rating: 21, tackle_rating: 17},
      {id: 40, position: "DT", name: "Speed Rusher", accel_rating: 8, agility_rating: 4, aware_rating: 8, block_shed_rating: 4, finesse_moves_rating: 22, hit_power_rating: 3, play_rec_rating: 8, pursuit_rating: 7, speed_rating: 6, strength_rating: 17, tackle_rating: 13},
      {id: 41, position: "LOLB", name: "Pass Coverage", accel_rating: 11, agility_rating: 4, aware_rating: 9, man_cover_rating: 10, play_rec_rating: 9, pursuit_rating: 12, speed_rating: 9, strength_rating: 2, tackle_rating: 14, zone_cover_rating: 20},
      {id: 42, position: "LOLB", name: "Power Rusher", accel_rating: 10, agility_rating: 2, aware_rating: 7, hit_power_rating: 2, man_cover_rating: 2, play_rec_rating: 7, power_moves_rating: 24, pursuit_rating: 12, speed_rating: 5, strength_rating: 8, tackle_rating: 15, zone_cover_rating: 6},
      {id: 43, position: "LOLB", name: "Run Stopper", accel_rating: 9, agility_rating: 2, aware_rating: 7, block_shed_rating: 16, hit_power_rating: 3, man_cover_rating: 2, play_rec_rating: 7, pursuit_rating: 16, speed_rating: 6, strength_rating: 10, tackle_rating: 16, zone_cover_rating: 6},
      {id: 44, position: "LOLB", name: "Speed Rusher", accel_rating: 13, agility_rating: 5, aware_rating: 7, finesse_moves_rating: 24, man_cover_rating: 2, play_rec_rating: 7, pursuit_rating: 10, speed_rating: 8, strength_rating: 6, tackle_rating: 12, zone_cover_rating: 6},
      {id: 45, position: "MLB", name: "Field General", accel_rating: 9, agility_rating: 7, aware_rating: 9, block_shed_rating: 7, man_cover_rating: 5, play_rec_rating: 9, pursuit_rating: 14, speed_rating: 5, strength_rating: 8, tackle_rating: 17, zone_cover_rating: 10},
      {id: 46, position: "MLB", name: "Pass Coverage", accel_rating: 10, agility_rating: 8, aware_rating: 7, man_cover_rating: 10, play_rec_rating: 7, pursuit_rating: 12, speed_rating: 7, strength_rating: 4, tackle_rating: 15, zone_cover_rating: 20},
      {id: 47, position: "MLB", name: "Run Stopper", accel_rating: 8, agility_rating: 7, aware_rating: 7, block_shed_rating: 9, finesse_moves_rating: 2, hit_power_rating: 2, man_cover_rating: 2, play_rec_rating: 7, power_moves_rating: 2, pursuit_rating: 15, speed_rating: 4, strength_rating: 10, tackle_rating: 20, zone_cover_rating: 5},
      {id: 48, position: "ROLB", name: "Pass Coverage", accel_rating: 11, agility_rating: 4, aware_rating: 9, man_cover_rating: 10, play_rec_rating: 9, pursuit_rating: 12, speed_rating: 9, strength_rating: 2, tackle_rating: 14, zone_cover_rating: 20},
      {id: 49, position: "ROLB", name: "Power Rusher", accel_rating: 10, agility_rating: 2, aware_rating: 7, hit_power_rating: 2, man_cover_rating: 2, play_rec_rating: 7, power_moves_rating: 24, pursuit_rating: 12, speed_rating: 5, strength_rating: 8, tackle_rating: 15, zone_cover_rating: 6},
      {id: 50, position: "ROLB", name: "Run Stopper", accel_rating: 9, agility_rating: 2, aware_rating: 7, block_shed_rating: 16, hit_power_rating: 3, man_cover_rating: 2, play_rec_rating: 7, pursuit_rating: 16, speed_rating: 6, strength_rating: 10, tackle_rating: 16, zone_cover_rating: 6},
      {id: 51, position: "ROLB", name: "Speed Rusher", accel_rating: 13, agility_rating: 5, aware_rating: 7, finesse_moves_rating: 24, man_cover_rating: 2, play_rec_rating: 7, pursuit_rating: 10, speed_rating: 8, strength_rating: 6, tackle_rating: 12, zone_cover_rating: 6},
      {id: 52, position: "CB", name: "Man to Man", accel_rating: 18, agility_rating: 4, aware_rating: 9, catch_rating: 2, jump_rating: 4, man_cover_rating: 22, play_rec_rating: 9, press_rating: 7, speed_rating: 20, tackle_rating: 3, zone_cover_rating: 2},
      {id: 53, position: "CB", name: "Slot", accel_rating: 14, agility_rating: 10, aware_rating: 9, block_shed_rating: 2, catch_rating: 2, jump_rating: 4, man_cover_rating: 14, play_rec_rating: 9, press_rating: 3, pursuit_rating: 4, speed_rating: 12, tackle_rating: 12, zone_cover_rating: 5},
      {id: 54, position: "CB", name: "Zone", accel_rating: 20, agility_rating: 4, aware_rating: 9, catch_rating: 2, jump_rating: 4, man_cover_rating: 4, play_rec_rating: 9, press_rating: 5, speed_rating: 18, tackle_rating: 5, zone_cover_rating: 20},
      {id: 55, position: "FS", name: "Hybrid", accel_rating: 11, agility_rating: 8, aware_rating: 10, jump_rating: 3, man_cover_rating: 15, play_rec_rating: 10, press_rating: 5, pursuit_rating: 4, speed_rating: 14, strength_rating: 2, tackle_rating: 11, zone_cover_rating: 7},
      {id: 56, position: "FS", name: "Run Support", accel_rating: 8, agility_rating: 6, aware_rating: 11, block_shed_rating: 2, hit_power_rating: 4, jump_rating: 3, man_cover_rating: 7, play_rec_rating: 11, press_rating: 3, pursuit_rating: 9, speed_rating: 9, strength_rating: 2, tackle_rating: 15, zone_cover_rating: 10},
      {id: 57, position: "FS", name: "Zone", accel_rating: 10, agility_rating: 8, aware_rating: 11, jump_rating: 3, man_cover_rating: 5, play_rec_rating: 11, pursuit_rating: 5, speed_rating: 14, strength_rating: 2, tackle_rating: 11, zone_cover_rating: 20},
      {id: 58, position: "SS", name: "Hybrid", accel_rating: 11, agility_rating: 8, aware_rating: 10, jump_rating: 3, man_cover_rating: 15, play_rec_rating: 10, press_rating: 5, pursuit_rating: 4, speed_rating: 14, strength_rating: 2, tackle_rating: 11, zone_cover_rating: 7},
      {id: 59, position: "SS", name: "Run Support", accel_rating: 8, agility_rating: 6, aware_rating: 11, block_shed_rating: 2, hit_power_rating: 4, jump_rating: 3, man_cover_rating: 7, play_rec_rating: 11, press_rating: 3, pursuit_rating: 9, speed_rating: 9, strength_rating: 2, tackle_rating: 15, zone_cover_rating: 10},
      {id: 60, position: "SS", name: "Zone", accel_rating: 10, agility_rating: 8, aware_rating: 11, jump_rating: 3, man_cover_rating: 5, play_rec_rating: 11, pursuit_rating: 5, speed_rating: 14, strength_rating: 2, tackle_rating: 11, zone_cover_rating: 20},
      {id: 61, position: "K", name: "Accurate", aware_rating: 40, kick_acc_rating: 60},
      {id: 62, position: "K", name: "Power", aware_rating: 40, kick_power_rating: 60},
      {id: 63, position: "P", name: "Accurate", aware_rating: 40, kick_acc_rating: 60},
      {id: 64, position: "P", name: "Power", aware_rating: 40, kick_power_rating: 60}
    ]
  end
end
